name: Test
on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  tests:
    strategy:
      matrix:
        node: [14.x, 15.x]
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install --prefer-offline --no-fund --no-progress
    - uses: microsoft/playwright-github-action@v1.5.0
    - run: npm test
